baseURL = "https://devopsdunkin.github.io/"
languageCode = "en-us"
title = "devops with dunkin"
theme = "paper"
paginate = 10
[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -120

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = -110

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = -100

  [[menu.icon]]
    url = "https://github.com/devopsdunkin"
    name = "fab fa-github"
    weight = 2

[params]
  githubUsername = "devopsdunkin"
  highlightLanguages = ["r", "bash", "go", "hcl", "python"]
  logo = "favicon/android-chrome-192x192.png"