baseURL = "https://devopsdunkin.github.io"
languageCode = "en-us"
title = "devops with dunkin"
theme = "paper"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = -110